import SideBar from '@/components/SideBar/SideBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className&&"text-[#444] bg-[#022c43] block overflow-hidden"}>
        <SideBar/>
        {children}
        </body>
    </html>
  )
}
